const playerProfiles = [
  {
    UID: "1234567890",
    username: "JohnDoe",
    email: "johndoe@example.com",
    score: 100,
    level: 5,
    verified: true,
    token: "eyJhbGc",
    joined: "2023-01-01",
    devices: ["realme", "iPhone"],
    lastLogin: "2023-01-01",
    country: "INDIA",
    city: "Mumbai",
  },
  {
    UID: "0987654321",
    username: "JaneSmith",
    email: "janesmith@example.com",
    score: 150,
    level: 7,
    verified: true,
    token: "eyJhbGc",
    joined: "2023-01-01",
    devices: ["Samsung", "iPad"],
    lastLogin: "2023-01-01",
    country: "INDIA",
    city: "Delhi",
  },
  {
    UID: "1122334455",
    username: "BobJohnson",
    email: "bobjohnson@example.com",
    score: 200,
    level: 10,
    verified: true,
    token: "eyJhbGc",
    joined: "2023-01-01",
    devices: ["Google Pixel", "MacBook"],
    lastLogin: "2023-01-01",
    country: "INDIA",
    city: "Bangalore",
  },
  {
    UID: "5566778899",
    username: "AliceBrown",
    email: "alicebrown@example.com",
    score: 180,
    level: 9,
    verified: true,
    token: "eyJhbGc",
    joined: "2023-01-01",
    devices: ["OnePlus", "Surface Pro"],
    lastLogin: "2023-01-01",
    country: "INDIA",
    city: "Chennai",
  },
  {
    UID: "6677889900",
    username: "kook",
    email: "kook@example.com",
    score: 120,
    level: 6,
    verified: true,
    token: "eyJhbGc",
    joined: "2023-01-01",
    devices: ["Xiaomi", "Dell XPS"],
    lastLogin: "2023-01-01",
    country: "INDIA",
    city: "Kolkata",
  },
  {
    UID: "7788990011",
    username: "daniel",
    email: "daniel@example.com",
    score: 160,
    level: 8,
    verified: true,
    token: "eyJhbGc",
    joined: "2023-01-01",
    devices: ["Huawei", "ThinkPad"],
    lastLogin: "2023-01-01",
    country: "INDIA",
    city: "Hyderabad",
  },
  {
    UID: "8899001122",
    username: "jogindar",
    email: "jogindar@example.com",
    score: 140,
    level: 7,
    verified: true,
    token: "eyJhbGc",
    joined: "2023-01-01",
    devices: ["Nokia", "ASUS VivoBook"],
    lastLogin: "2023-01-01",
    country: "INDIA",
    city: "Pune",
  },
  {
    UID: "9900112233",
    username: "maria",
    email: "maria@example.com",
    score: 170,
    level: 8,
    verified: true,
    token: "eyJhbGc",
    joined: "2023-01-01",
    devices: ["Motorola", "LG Gram"],
    lastLogin: "2023-01-01",
    country: "INDIA",
    city: "Ahmedabad",
  },
];

module.exports = playerProfiles;
